### ISSUE TITLE
Links de laboratórios e departamentos entram em qual categoria?

### ISSUE THREAD

**Issue by Camilotk** [adolfont/computacaobrasil#2]
Laboratórios de Faculdades de Computação como o [LABIC](http://labic.icmc.usp.br/) do ICMC da USP reúnem vários trabalhos, publicações, eventos e atividades, seriam uma categoria à parte ou entram em Organizações?

**Comment by adolfont** [comment]
Eu sugiro criar uma nova categoria, no fim
